'use client'
import { ClerkProvider } from '@clerk/nextjs'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import useSyncUser from '@/hooks/useSyncUser';
import { Provider } from 'react-redux'
import { store } from './store';

const SyncUserWrapper = ({ children }) => {
  useSyncUser();
  return <>{children}</>;
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <ClerkProvider>
      <Provider store={store} >

        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <SyncUserWrapper>
              {children}
            </SyncUserWrapper>
          </body>
        </html>
      </Provider>
    </ClerkProvider>
  );
}
